server:
  port: 8081

spring:
  application:
    name: order

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/order_db}
    username: ${DATABASE_USERNAME:store}
    password: ${DATABASE_PASSWORD:store123}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: orders
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: orders

logging:
  level:
    store: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8080}
